remote: true

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: true
  temporary: true
  internship: false
  other: false
  volunteer: true

date:
  all time: false
  month: false
  week: true
  24 hours: true

positions:
  - Computer Instructor
  - Digital Literacy Trainer
  - IT Support Specialist
  - AI Automation
  - Social Media Administrator
  - Administrative Assistant

locations:
  - Edmonton, Alberta, Canada
  - Canada
  - Remote

apply_once_at_company: true

distance: 50

company_blacklist:
  - Crossover

title_blacklist:
  - Senior Director
  - VP

location_blacklist: []

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 150

max_daily_applications: 5

llm_model_type: openai
llm_model: 'gpt-4o-mini'
